"""add_nutrition_models

Revision ID: 002
Revises: 001
Create Date: 2026-02-02 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    
    # 1. Ingredients
    op.create_table('ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('glycemic_index', sa.Integer(), nullable=False),
    sa.Column('carbs_per_100g', sa.Float(), nullable=False),
    sa.Column('fiber_per_100g', sa.Float(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)
    op.create_index(op.f('ix_ingredients_barcode'), 'ingredients', ['barcode'], unique=False)

    # 2. Meal Logs
    op.create_table('meals_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('total_carbs_grams', sa.Float(), nullable=False),
    sa.Column('total_glycemic_load', sa.Float(), nullable=False),
    sa.Column('notes', sa.LargeBinary(), nullable=True), # Encrypted
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_log_timestamp'), 'meals_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_meals_log_user_id'), 'meals_log', ['user_id'], unique=False)

    # 3. Meal Items (Join Table)
    op.create_table('meal_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('weight_grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_meals_log_user_id'), table_name='meals_log')
    op.drop_index(op.f('ix_meals_log_timestamp'), table_name='meals_log')
    op.drop_table('meals_log')
    op.drop_index(op.f('ix_ingredients_barcode'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
